config/routes.rb
Rails.application.routes.draw do

  mount_griddler

  devise_for :users

  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
    get "signup", to: "devise/registrations#new"
  end

  resources :exercises
  resources :routines
  resources :workouts
end

app/models/concerns/uuid_to_param.rb
module UuidToParam
  extend ActiveSupport::Concern

  def to_param
    uuid
  end
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  include UuidToParam

  belongs_to :user
  has_many :exercise_sets

  validates :user, presence: true
end

app/models/exercise_set.rb
class ExerciseSet < ActiveRecord::Base
  include UuidToParam

  belongs_to :exercise
  belongs_to :workout

  validates :exercise, presence: true
  validates :workout, presence: true

  scope :sorted_by_date, -> { joins(:workout).order("workouts.date asc") }
  scope :sorted_by_type, -> { order(exercise_id: :asc, order: :asc) }
  scope :sorted_by_weight, -> { order(weight: :asc, reps: :asc) }

  before_create :calculate_weights

  def calculate_weights
    if weight.present? && reps.present?
      self.one_rep_max = calculate_one_rep_max
      self.volume = calculate_volume
    end
  end

  def calculate_one_rep_max
    "%.2f" % (weight.to_f * (36 / (37 - reps.to_f)))
  end

  def calculate_volume
    weight.to_f * reps
  end
end

app/models/routine.rb
class Routine < ActiveRecord::Base
  include UuidToParam

  belongs_to :user
  has_many :workouts

  validates :user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  include UuidToParam
  
  devise :confirmable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :exercises
  has_many :routines
  has_many :workouts, through: :routines

  def self.find_or_create_by_email(email)
    user = User.find_by_email(email)

    if user.blank?
      user = User.create(
        email: email,
        password: SecureRandom.hex(16)
      )
    end

    user
  end
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  include UuidToParam

  belongs_to :routine
  has_many :exercise_sets

  validates :routine, presence: true

  scope :sorted_by_date, -> { order("date asc") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def index
    @exercises = ExerciseDecorator.decorate_collection(
      current_user.exercises.includes(:exercise_sets)
    )
  end

  def show
    @exercise = current_user.exercises.find_by_uuid(params[:id]).decorate

    @exercise_sets = ExerciseSetDecorator.decorate_collection(
      @exercise.exercise_sets
    )

    @chart = ChartBuilder.new(
      @exercise,
      params[:time_interval],
      params[:query_type],
      params[:measure]
    )
  end
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  def index
    @routines = RoutineDecorator.decorate_collection(
      current_user.routines
    )
  end

  def show
    @routine = current_user.routines.find_by_uuid(params[:id])

    @workouts = WorkoutDecorator.decorate_collection(
      @routine.workouts
    )
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  def index
    @workouts = WorkoutDecorator.decorate_collection(
      current_user.workouts.includes(:routine)
    )
  end

  def show
    @workout = current_user.workouts.find_by_uuid(params[:id]).decorate

    @exercise_groups = ExerciseSetDecorator.decorate_collection(
      @workout.exercise_sets.sorted_by_type
    ).group_by(&:exercise)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chart_helper.rb
module ChartHelper
  def chart_filter filter_text, filter_type, filter_value, default: false
    classes = ["btn"]
    filter_param = params[filter_type]
    active = (filter_param == filter_value) || (filter_param.blank? && default)

    if active
      classes << ["active"]
    end

    link_params = {}

    ["time_interval", "query_type", "measure"].each do |param|
      if params[param]
        link_params[param] = params[param]
      end
    end

    link_params[filter_type] = filter_value

    link_to filter_text, link_params, class: classes.join(" ")
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_css_overrides.slim
- if Rails.env.test?
  css:
    * {
      transition-property: none !important;
      -webkit-transition-property: none !important;
    }

app/views/application/_flashes.slim
- if flash.any?
  .flashes
    - user_facing_flashes.each do |key, value|
      div[class="flash-#{key}"]
        = value

app/views/application/_javascript.slim
= yield :javascript

- if Rails.env.test?
  javascript:
    $.fx.off = true;
    $.ajaxSetup({ async: false });

app/views/exercises/index.slim
h4.m-b-2
  | Exercises

.table
  .table-header
    .col-sm-3
      | Exercise
    .col-sm-3
      | Personal Record
    .col-sm-3
      | Last Completed
    .col-sm-3
      | Total sets
  - @exercises.each do |exercise|
    = link_to exercise_path(exercise), class: "table-row" do
      .col-sm-3
        = exercise.name
      .col-sm-3
        = exercise.personal_record_set.weight_and_reps
      .col-sm-3
        = exercise.most_recent_set.workout_date
      .col-sm-3
        = exercise.exercise_sets.count

app/views/exercises/show.slim
h4.m-b-2
  = link_to "Exercises", exercises_path
  = " - "
  = @exercise.name

= line_chart @chart.data, library: @chart.options

.m-b-2.text-sm-center
  .btn-group.m-r-2
    = chart_filter "Day", "time_interval", "day", default: true
    = chart_filter "Week", "time_interval", "week"

  .btn-group.m-r-2
    = chart_filter "Maximum", "query_type", "maximum", default: true
    = chart_filter "Average", "query_type", "average"

  .btn-group
    = chart_filter "Weight", "measure", "weight", default: true
    = chart_filter "1RM", "measure", "one_rep_max"
    = chart_filter "Volume", "measure", "volume"

.table
  .table-header
    .col-sm-2
      | Exercise Date
    .col-sm-2
      | Weight
    .col-sm-2
      | 1RM
    .col-sm-2
      | Volume
    .col-sm-2
      | Reps
    .col-sm-2
      | Set Order
  - @exercise_sets.each do |set|
    .table-row
      .col-sm-2
        = set.workout_date
      .col-sm-2
        = set.weight_with_units
      .col-sm-2
        = set.one_rep_max_with_units
      .col-sm-2
        = set.volume_with_units
      .col-sm-2
        = set.reps
      .col-sm-2
        = set.order

app/views/layouts/application.slim
doctype html
html[lang="en"]
  head
    meta[charset="utf-8"]
    meta[name="ROBOTS" content="NOODP"]
    meta[name="viewport" content="initial-scale=1"]

    title
      = title

    = stylesheet_link_tag :application, media: "all"
    = javascript_include_tag :application
    = javascript_include_tag "https://www.google.com/jsapi", "chartkick"
    = csrf_meta_tags

  body[class=body_class]
    = render "flashes"

    .container
      = yield

    = render "javascript"
    = render "css_overrides"

app/views/routines/index.slim
h4.m-b-2
  | Routines

.table
  .table-header
    .col-sm-3
      | Routine
    .col-sm-3
      | Last Workout
    .col-sm-3
      | Workouts
    .col-sm-3
  - @routines.each do |routine|
    = link_to routine, class: "table-row" do
      .col-sm-3
        = routine.name
      .col-sm-3
        = routine.most_recent_workout.workout_date
      .col-sm-3
        = routine.workouts.count
      .col-sm-3

app/views/routines/show.slim
h4.m-b-2
  = link_to "Routines", routines_path
  = " - "
  = @routine.name

.table
  .table-header
    .col-sm-3
      | Workout date
    .col-sm-3
      | Exercises
    .col-sm-3
      | Exercise Sets
    .col-sm-3
  - @workouts.each do |workout|
    = link_to workout_path(workout), class: "table-row" do
      .col-sm-3
        = workout.workout_date
      .col-sm-3
        = workout.exercise_sets.group_by(&:exercise).count
      .col-sm-3
        = workout.exercise_sets.count
      .col-sm-3

app/views/workouts/index.slim
h4.m-b-2
  | Workouts

.table
  .table-header
    .col-sm-3
      | Workout Date
    .col-sm-3
      | Routine
    .col-sm-3
      | Exercises
    .col-sm-3
      | Total Sets
  - @workouts.each do |workout|
    = link_to workout_path(workout), class: "table-row" do
      .col-sm-3
        = workout.workout_date
      .col-sm-3
        = workout.routine.name
      .col-sm-3
        = workout.exercise_sets.group_by(&:exercise).count
      .col-sm-3
        = workout.exercise_sets.count

app/views/workouts/show.slim
h4.m-b-2
  = link_to "Workouts", workouts_path
  = " - "
  = @workout.workout_date
  = " - "
  = @workout.routine.name

- @exercise_groups.each do |exercise_group|
  .table
    .table-header
      .col-sm-3
        = link_to exercise_group[0].name, exercise_group[0] 
      .col-sm-3
        | Weight
      .col-sm-3
        | 1RM
      .col-sm-3
        | Volume
    - exercise_group[1].each do |set|
      .table-row
        .col-sm-3
          = set.order
        .col-sm-3
          = set.weight_and_reps
        .col-sm-3
          = set.one_rep_max_with_units
        .col-sm-3
          = set.volume_with_units